all:
	

.PHONY: clean
clean:
	@rm -rf .bin
	@rm -f *.ufsl *.fsl *.fas *.x86f *.sparcf *.fasl 
	@rm -f *.fasla8 *.fasla16 *.faslm8 *.faslm16 *.faslmt
	@rm -f *~ *.bak *.orig *.err \#*\# .#*
	@rm -f *.so *.a
	@rm -rf debian/cl-uffi
ifneq ($(SUBDIRS)$(DOCSUBDIRS),)
	@set -e; for i in $(SUBDIRS) $(DOCSUBDIRS); do \
		$(MAKE) -C $$i $@; done
endif

.SUFFIXES:            # No default suffixes
